### ISSUE TITLE
Cannot add node to map in v3

### ISSUE THREAD

**Issue by piotrpekala7** [GNS3/gns3-web-ui#1122]
Endpoint: /v3/projects/{project_id}/templates/{template_id} doesn't work properly for web UI. 

When user try to add node following error appears: 4200/server/22/project/a0e116ab-46b5-4aaf-929d-09abcf5093cc:1 Access to XMLHttpRequest at 'http://127.0.0.1:3080/v3/projects/a0e116ab-46b5-4aaf-929d-09abcf5093cc/templates/19021f99-e36f-394d-b4a1-8aaa902ab9cc' from origin 'http://localhost:4200' has been blocked by CORS policy: No 'Access-Control-Allow-Origin' header is present on the requested resource.

**Comment by piotrpekala7** [comment]
![30 04](https://user-images.githubusercontent.com/31202938/116684884-d56e1900-a9b1-11eb-9bac-0a24fd4f20e5.PNG)
headers in request are correct

**Comment by grossmj** [comment]
Apparently due to an exception in GNS3 server

```
Traceback (most recent call last):
  File "/home/grossmj/PycharmProjects/gns3-server/venv-test/lib/python3.8/site-packages/uvicorn-0.13.4-py3.8.egg/uvicorn/protocols/http/h11_impl.py", line 396, in run_asgi
    result = await app(self.scope, self.receive, self.send)
  File "/home/grossmj/PycharmProjects/gns3-server/venv-test/lib/python3.8/site-packages/uvicorn-0.13.4-py3.8.egg/uvicorn/middleware/proxy_headers.py", line 45, in __call__
    return await self.app(scope, receive, send)
  File "/home/grossmj/PycharmProjects/gns3-server/venv-test/lib/python3.8/site-packages/fastapi-0.63.0-py3.8.egg/fastapi/applications.py", line 199, in __call__
    await super().__call__(scope, receive, send)
  File "/home/grossmj/PycharmProjects/gns3-server/venv-test/lib/python3.8/site-packages/starlette-0.13.6-py3.8.egg/starlette/applications.py", line 111, in __call__
    await self.middleware_stack(scope, receive, send)
  File "/home/grossmj/PycharmProjects/gns3-server/venv-test/lib/python3.8/site-packages/starlette-0.13.6-py3.8.egg/starlette/middleware/errors.py", line 181, in __call__
    raise exc from None
  File "/home/grossmj/PycharmProjects/gns3-server/venv-test/lib/python3.8/site-packages/starlette-0.13.6-py3.8.egg/starlette/middleware/errors.py", line 159, in __call__
    await self.app(scope, receive, _send)
  File "/home/grossmj/PycharmProjects/gns3-server/venv-test/lib/python3.8/site-packages/starlette-0.13.6-py3.8.egg/starlette/middleware/base.py", line 25, in __call__
    response = await self.dispatch_func(request, self.call_next)
  File "/home/grossmj/PycharmProjects/gns3-server/gns3server/api/server.py", line 166, in add_extra_headers
    response = await call_next(request)
  File "/home/grossmj/PycharmProjects/gns3-server/venv-test/lib/python3.8/site-packages/starlette-0.13.6-py3.8.egg/starlette/middleware/base.py", line 45, in call_next
    task.result()
  File "/home/grossmj/PycharmProjects/gns3-server/venv-test/lib/python3.8/site-packages/starlette-0.13.6-py3.8.egg/starlette/middleware/base.py", line 38, in coro
    await self.app(scope, receive, send)
  File "/home/grossmj/PycharmProjects/gns3-server/venv-test/lib/python3.8/site-packages/starlette-0.13.6-py3.8.egg/starlette/middleware/cors.py", line 86, in __call__
    await self.simple_response(scope, receive, send, request_headers=headers)
  File "/home/grossmj/PycharmProjects/gns3-server/venv-test/lib/python3.8/site-packages/starlette-0.13.6-py3.8.egg/starlette/middleware/cors.py", line 142, in simple_response
    await self.app(scope, receive, send)
  File "/home/grossmj/PycharmProjects/gns3-server/venv-test/lib/python3.8/site-packages/starlette-0.13.6-py3.8.egg/starlette/exceptions.py", line 82, in __call__
    raise exc from None
  File "/home/grossmj/PycharmProjects/gns3-server/venv-test/lib/python3.8/site-packages/starlette-0.13.6-py3.8.egg/starlette/exceptions.py", line 71, in __call__
    await self.app(scope, receive, sender)
  File "/home/grossmj/PycharmProjects/gns3-server/venv-test/lib/python3.8/site-packages/starlette-0.13.6-py3.8.egg/starlette/routing.py", line 566, in __call__
    await route.handle(scope, receive, send)
  File "/home/grossmj/PycharmProjects/gns3-server/venv-test/lib/python3.8/site-packages/starlette-0.13.6-py3.8.egg/starlette/routing.py", line 227, in handle
    await self.app(scope, receive, send)
  File "/home/grossmj/PycharmProjects/gns3-server/venv-test/lib/python3.8/site-packages/starlette-0.13.6-py3.8.egg/starlette/routing.py", line 41, in app
    response = await func(request)
  File "/home/grossmj/PycharmProjects/gns3-server/venv-test/lib/python3.8/site-packages/fastapi-0.63.0-py3.8.egg/fastapi/routing.py", line 201, in app
    raw_response = await run_endpoint_function(
  File "/home/grossmj/PycharmProjects/gns3-server/venv-test/lib/python3.8/site-packages/fastapi-0.63.0-py3.8.egg/fastapi/routing.py", line 148, in run_endpoint_function
    return await dependant.call(**values)
  File "/home/grossmj/PycharmProjects/gns3-server/gns3server/api/routes/controller/templates.py", line 145, in create_node_from_template
    node = await project.add_node_from_template(
  File "/home/grossmj/PycharmProjects/gns3-server/gns3server/controller/project.py", line 525, in add_node_from_template
    template["x"] = x
TypeError: 'coroutine' object does not support item assignment

```

**Comment by grossmj** [comment]
Fixed
