### ISSUE TITLE
Cannot update packages to the latest version

### ISSUE THREAD

**Issue by piotrpekala7** [GNS3/gns3-web-ui#1150]
When trying to update all web UI dependencies to the latest version following error appears

> Error: The target entry-point "angular-persistence" has missing dependencies:
>  - rxjs/Rx
> 
>     at TargetedEntryPointFinder.findEntryPoints (C:\Users\piotr.pekala\Desktop\gns3-web-ui\node_modules\@angular\compiler-cli\ngcc\src\entry_point_finder\targeted_entry_point_finder.js:40:23)
>     at C:\Users\piotr.pekala\Desktop\gns3-web-ui\node_modules\@angular\compiler-cli\ngcc\src\execution\analyze_entry_points.js:29:41
>     at SingleProcessExecutorSync.SingleProcessorExecutorBase.doExecute (C:\Users\piotr.pekala\Desktop\gns3-web-ui\node_modules\@angular\compiler-cli\ngcc\src\execution\single_process_executor.js:28:29)
>     at C:\Users\piotr.pekala\Desktop\gns3-web-ui\node_modules\@angular\compiler-cli\ngcc\src\execution\single_process_executor.js:57:59
>     at SyncLocker.lock (C:\Users\piotr.pekala\Desktop\gns3-web-ui\node_modules\@angular\compiler-cli\ngcc\src\locking\sync_locker.js:34:24)
>     at SingleProcessExecutorSync.execute (C:\Users\piotr.pekala\Desktop\gns3-web-ui\node_modules\@angular\compiler-cli\ngcc\src\execution\single_process_executor.js:57:27)
>     at Object.mainNgcc (C:\Users\piotr.pekala\Desktop\gns3-web-ui\node_modules\@angular\compiler-cli\ngcc\src\main.js:74:25)
>     at Object.process (C:\Users\piotr.pekala\Desktop\gns3-web-ui\node_modules\@angular\compiler-cli\ngcc\index.js:29:23)
>     at NgccProcessor.processModule (C:\Users\piotr.pekala\Desktop\gns3-web-ui\node_modules\@angular-devkit\build-angular\node_modules\@ngtools\webpack\src\ngcc_processor.js:164:16)
>     at C:\Users\piotr.pekala\Desktop\gns3-web-ui\node_modules\@angular-devkit\build-angular\node_modules\@ngtools\webpack\src\ivy\host.js:128:18
>     at C:\Users\piotr.pekala\Desktop\gns3-web-ui\node_modules\@angular-devkit\build-angular\node_modules\@ngtools\webpack\src\ivy\host.js:58:24
>     at Array.map (<anonymous>)
>     at Object.host.resolveModuleNames (C:\Users\piotr.pekala\Desktop\gns3-web-ui\node_modules\@angular-devkit\build-angular\node_modules\@ngtools\webpack\src\ivy\host.js:56:32)
>     at actualResolveModuleNamesWorker (C:\Users\piotr.pekala\Desktop\gns3-web-ui\node_modules\typescript\lib\typescript.js:106560:133)
>     at resolveModuleNamesWorker (C:\Users\piotr.pekala\Desktop\gns3-web-ui\node_modules\typescript\lib\typescript.js:106810:26)
>     at resolveModuleNamesReusingOldState (C:\Users\piotr.pekala\Desktop\gns3-web-ui\node_modules\typescript\lib\typescript.js:106907:24)

**Comment by piotrpekala7** [comment]
will be fixed in https://github.com/GNS3/gns3-web-ui/pull/1157
