### ISSUE TITLE
WebSocket failed over Nginx Reverse Proxy

### ISSUE THREAD

**Issue by Flaxee** [GNS3/gns3-web-ui#753]
I'm trying to access the WebUI over a Nginx Reverse Proxy but getting the following error message when opening up a project.
Similar to issue #447 

As @piotrpekala7  said in the above issue, it looks like the server port is missing.
Could this be because the page is being loaded over HTTPS, but it's attempting to coonect to an insecure WebSocket (ws) instead of a secure WebSocket (wss)?

```
main.89a8d561ddbdc1d9fa28.js:1 DOMException: Failed to construct 'WebSocket': The URL 'ws://gns3.domain.com:NaN/v2/projects/4cb4c189-bdf6-4c2f-a7c7-99360eeaafee/notifications/ws' is invalid.
    at n.setUpProjectWS (https://gns3.domain.com/static/web-ui/main.89a8d561ddbdc1d9fa28.js:1:3408526)
    at e._next (https://gns3.domain.com/static/web-ui/main.89a8d561ddbdc1d9fa28.js:1:3408381)
    at e.__tryOrUnsub (https://gns3.domain.com/static/web-ui/main.89a8d561ddbdc1d9fa28.js:1:412200)
    at e.next (https://gns3.domain.com/static/web-ui/main.89a8d561ddbdc1d9fa28.js:1:411345)
    at e._next (https://gns3.domain.com/static/web-ui/main.89a8d561ddbdc1d9fa28.js:1:410421)
    at e.next (https://gns3.domain.com/static/web-ui/main.89a8d561ddbdc1d9fa28.js:1:410092)
    at e.notifyNext (https://gns3.domain.com/static/web-ui/main.89a8d561ddbdc1d9fa28.js:1:664293)
    at e._next (https://gns3.domain.com/static/web-ui/main.89a8d561ddbdc1d9fa28.js:1:671184)
    at e.next (https://gns3.domain.com/static/web-ui/main.89a8d561ddbdc1d9fa28.js:1:410092)
    at e._next (https://gns3.domain.com/static/web-ui/main.89a8d561ddbdc1d9fa28.js:1:410421)
    at e.next (https://gns3.domain.com/static/web-ui/main.89a8d561ddbdc1d9fa28.js:1:410092)
    at e._next (https://gns3.domain.com/static/web-ui/main.89a8d561ddbdc1d9fa28.js:1:96546)
    at e.next (https://gns3.domain.com/static/web-ui/main.89a8d561ddbdc1d9fa28.js:1:410092)
    at e._next (https://gns3.domain.com/static/web-ui/main.89a8d561ddbdc1d9fa28.js:1:556043)
    at e.next (https://gns3.domain.com/static/web-ui/main.89a8d561ddbdc1d9fa28.js:1:410092)
    at e.notifyNext (https://gns3.domain.com/static/web-ui/main.89a8d561ddbdc1d9fa28.js:1:664293)
    at e._next (https://gns3.domain.com/static/web-ui/main.89a8d561ddbdc1d9fa28.js:1:671184)
    at e.next (https://gns3.domain.com/static/web-ui/main.89a8d561ddbdc1d9fa28.js:1:410092)
    at XMLHttpRequest.s (https://gns3.domain.com/static/web-ui/main.89a8d561ddbdc1d9fa28.js:1:1039400)
    at XMLHttpRequest.o (https://gns3.domain.com/static/web-ui/main.89a8d561ddbdc1d9fa28.js:1:610806)
    at e.invokeTask (https://gns3.domain.com/static/web-ui/polyfills.b9cf08f4f6defdfd6c4f.js:1:8079)
    at Object.onInvokeTask (https://gns3.domain.com/static/web-ui/main.89a8d561ddbdc1d9fa28.js:1:336863)
    at e.invokeTask (https://gns3.domain.com/static/web-ui/polyfills.b9cf08f4f6defdfd6c4f.js:1:8000)
    at t.runTask (https://gns3.domain.com/static/web-ui/polyfills.b9cf08f4f6defdfd6c4f.js:1:3158)
    at t.invokeTask [as invoke] (https://gns3.domain.com/static/web-ui/polyfills.b9cf08f4f6defdfd6c4f.js:1:9211)
    at b (https://gns3.domain.com/static/web-ui/polyfills.b9cf08f4f6defdfd6c4f.js:1:22639)
    at XMLHttpRequest._ (https://gns3.domain.com/static/web-ui/polyfills.b9cf08f4f6defdfd6c4f.js:1:22942)
```

My Nginx location block look like the following, and works fine for other applications which also use WebSockets:
```
    location / {
        proxy_pass http://10.10.10.201:3080;
        proxy_set_header Host $host;
        proxy_set_header X-Real-IP $remote_addr;
        proxy_set_header X-Forwarded-Host $server_name;
        proxy_set_header X-Forwarded-For $proxy_add_x_forwarded_for;
        proxy_set_header X-Forwarded-Proto $scheme;
        proxy_set_header X-Forwarded-Ssl on;

        # Disable buffering to serve data immediately to clients.
        # The max_body_size is increased to 1 GB to allow uploads of big files via the Web UI.
        proxy_buffering off;
        proxy_buffer_size 4k;
        client_max_body_size 1g;
        proxy_connect_timeout 90;
        proxy_send_timeout 90;
        proxy_read_timeout 90;
        proxy_redirect off;

        # Allow websockets
        proxy_http_version 1.1;
        proxy_set_header Upgrade $http_upgrade;
        proxy_set_header Connection "upgrade";
    }
```

**Comment by piotrpekala7** [comment]
Is this issue still in the latest version?

**Comment by Flaxee** [comment]
I'm currently running version 2.2.5, which seem to be the latest GNS3 release.
Should I git pull the gns3-server or gns3-web-ui repo to tryout the latest versions?

**Comment by piotrpekala7** [comment]
I am sorry, we cannot connect to the server via https & wss in the current version. We will want to implement the necessary changes in the near future.

**Comment by wkrea** [comment]
Any notice about this improve @piotrpekala7?

Thanks
